### ISSUE TITLE
Wishlist: link check that works with anchors

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs#29]
sometimes internal links that use anchors to link to specific sections break because the anchor ID is later changed (meaning the link takes you to the correct page, but does not bounce you to the intended subsection)

it would be great if the link checking was able to dereference anchors to make sure they exist on the target page (I suppose this could be implemented on internal pages as well as external pages. but for sure, the priority here is internal pages)

**Comment by amotl** [comment]
Hi Naomi,

I don't know much about this yet, but it might be the case that Sphinx's `linkcheck` builder already features the `linkcheck_anchors` configuration setting since Sphinx 1.2. The documentation says it is enabled by default [1].

> If true, check the validity of `#anchor`s in links. Since this requires downloading the whole document, it’s considerably slower when enabled. Default is `True`.

In this context, https://github.com/sphinx-doc/sphinx/issues/4303 and https://github.com/sphinx-doc/sphinx/issues/5128 might be relevant.

With kind regards,
Andreas.

[1] https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_anchors

**Comment by mechanomi** [comment]
you're right! thanks! marking as closed!
